name: Daily Script Run

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: go to tweet-import
        run: cd tweet-import

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scrape-tweets/requirements.txt

      - name: Run Python script
        run: python tweet-import/scrape-tweets/main.py

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun tweet-import/supabase-add.ts
