name: Daily Script Run

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  run_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: List directory contents
        run: |
          echo "Current directory:"
            pwd
          echo "Contents:"
          ls -R

      - name: Install Python dependencies
        run: pip install twitter-api-client

      - name: Run Python script
        env:
          ct0: ${{ secrets.CT0 }}
          auth_token: ${{ secrets.AUTH_TOKEN }}
        run: python import-tweets/main.py

      - name: Set up bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run script
        run: bun import-tweets/supabase-add.ts
